spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.cmucpyrne67h.ap-northeast-2.rds.amazonaws.com:3306/rotten?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: rlqja1212
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-id: "859588785984-gl9ufkend5flgvkfqi4840dqknauk7vj.apps.googleusercontent.com"
            client-secret: ""
            scope:
              - email
              - profile
#        AWS S3
cloud:
  aws:
    s3:
      bucket: daefafa
    credentials:
      access-key: 'AKIAZPWBCDMQTL7D5RL4'
      secret-key: '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'
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR